name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Hello_github_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: echo "Hello, GitHub Actions!"
      